# Minecraft 版本
minecraft_version=1.21.5
# Yarn 映射版本
yarn_mappings=1.21.5+build.1
# Fabric Loader 版本
loader_version=0.16.14
# Fabric API 版本
fabric_version=0.119.2+1.21.5
# Loom 版本（1.21.x 使用混淆 remap Loom）
loom_version=1.14.10
# Java 版本
java_version=21

# Mod 元数据
maven_group=com.chayewuu.hyperheartrate
archive_base_name=hyper-heartrate
mod_version=1.3.0

# Gradle 配置
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
