# Minecraft 版本
minecraft_version=26.2
# Fabric Loader 版本
loader_version=0.19.3
# Fabric API 版本
fabric_version=0.152.0+26.2
# Loom 版本
loom_version=1.17.17
# Java 版本
java_version=25

# Mod 元数据
maven_group=com.chayewuu.hyperheartrate
archive_base_name=hyper-heartrate
mod_version=1.3.0

# Gradle 配置
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
